object Versions{
const val kotlin = "1.3.72"
    const val gradle = "3.6.3"
    const val appcompat = "1.1.0"
    const val coreKtx = "1.2.0"
    const val constraintLayout = "1.1.3"
    const val junit = "4.12"
    const val extJunit = "1.1.1"
    const val espressoCore = "3.2.0"
    const val material = "1.1.0"
    const val lifecycle = "2.2.0"
    const val room = "2.2.5"
    const val retrofit = "2.7.1"
    const val okhttp = "4.3.1"
    const val gson = "2.8.6"
    const val glide = "4.11.0"
    const val navigation = "2.3.0"
    const val coroutines = "1.3.7"
    const val hilt = "2.28-alpha"
    const val hiltViewModel = "1.0.0-alpha01"
    const val hiltCompiler = "1.0.0-alpha01"
    const val viewModel = "1.1.1"
    const val lifecycleCompiler = "2.2.0"
    const val roomCompiler = "2.2.5"
    const val retrofitConverter = "2.7.1"

}